### ISSUE TITLE
Google maps seems broken

### ISSUE THREAD

**Issue by dennisdegreef** [AmsterdamPHP/amsterdamphp.nl#95]
It seems that Google Maps doesn't want to load anymore, it may have something to do with API keys

**Comment by WyriHaximus** [comment]
Works on my machine: 
![screenshot from 2017-03-07 07 59 47](https://cloud.githubusercontent.com/assets/147145/23645411/33c86bdc-030c-11e7-9222-82217d92c5f2.png)

**Comment by WyriHaximus** [comment]
@dennisdegreef file #96 to fix this. I was visiting the site over HTTP, when testing it over HTTPS it broke
